# Generated by Django 4.2.1 on 2023-05-27 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='museum.hall'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='museum.position'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='exhibition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='exhibit', to='museum.exhibition'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='exposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='exhibit', to='museum.exposition'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibit', to='museum.hall'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='observer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='exhibit', to='museum.employee'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition', to='museum.theme'),
        ),
        migrations.AlterField(
            model_name='exposition',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposition', to='museum.theme'),
        ),
    ]
