# Generated by Django 4.2.1 on 2023-06-03 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='temp', help_text='Enter password. In future u cant see it in admin panel', max_length=20, validators=[django.core.validators.MinLengthValidator(8)]),
            preserve_default=False,
        ),
    ]
