# Generated by Django 4.2.1 on 2023-05-28 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_alter_employee_hall_alter_employee_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='exhibition',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exhibit', to='museum.exhibition'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='exposition',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exhibit', to='museum.exposition'),
        ),
    ]
