# Generated by Django 4.2.1 on 2023-05-30 16:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_alter_exhibit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular exhibit', primary_key=True, serialize=False),
        ),
    ]
