# Generated by Django 4.2.1 on 2023-06-05 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_employee_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
    ]
