# Generated by Django 4.2.1 on 2023-05-28 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0003_alter_exhibit_exhibition_alter_exhibit_exposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='exhibition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exhibit', to='museum.exhibition'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='exposition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exhibit', to='museum.exposition'),
        ),
    ]
