# Generated by Django 4.2.1 on 2023-06-01 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0003_alter_exhibit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='observer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='museum.employee'),
        ),
    ]
