# Generated by Django 4.2.1 on 2023-06-01 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0004_alter_exhibit_observer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum.hall'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='observer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='exhibit', to='museum.employee'),
        ),
    ]
