# Generated by Django 4.2.1 on 2023-05-28 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0004_alter_exhibit_exhibition_alter_exhibit_exposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibit',
            name='art_form',
        ),
        migrations.AddField(
            model_name='exhibit',
            name='art_form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exhibit', to='museum.artform'),
            preserve_default=False,
        ),
    ]
