# Generated by Django 4.2.1 on 2023-06-01 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0005_alter_exhibit_hall_alter_exhibit_observer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibit', to='museum.hall'),
        ),
    ]
