# Generated by Django 4.2.1 on 2023-06-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0008_alter_exhibit_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='photo',
            field=models.URLField(default=''),
        ),
    ]
